// <auto-generated />
using HeroPassport.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroPassport.Infrastructure.Persistence.GeneratedMigrations
{
    [DbContext(typeof(HeroPassportDbContext))]
    [Migration("20260813125843_InitialFoundation")]
    partial class InitialFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("HeroPassport.Storage.AppSettings", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("active_hero_id")
                        .HasColumnType("TEXT");

                    b.Property<int>("auto_finish_quest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("auto_start_quest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("config_version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("created_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("locale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("presentation_style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("project_identity_salt_v1")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("setup_completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("updated_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("active_hero_id");

                    b.ToTable("app_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_settings_auto_finish", "auto_finish_quest IN (0,1)");

                            t.HasCheckConstraint("ck_app_settings_auto_start", "auto_start_quest IN (0,1)");

                            t.HasCheckConstraint("ck_app_settings_config_version", "config_version >= 1");

                            t.HasCheckConstraint("ck_app_settings_locale", "locale IN ('ru-RU','en-US')");

                            t.HasCheckConstraint("ck_app_settings_presentation_style", "presentation_style IN ('rpg_engineering','classic_rpg','minimal')");

                            t.HasCheckConstraint("ck_app_settings_salt", "length(project_identity_salt_v1) = 32");

                            t.HasCheckConstraint("ck_app_settings_setup_active_hero", "(setup_completed = 0 AND active_hero_id IS NULL) OR (setup_completed = 1 AND active_hero_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_app_settings_setup_completed", "setup_completed IN (0,1)");

                            t.HasCheckConstraint("ck_app_settings_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.Hero", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("archived_at_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("created_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("strain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(20);

                    b.Property<long>("success_streak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<long>("total_xp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int>("trust")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(50);

                    b.Property<string>("updated_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("heroes", null, t =>
                        {
                            t.HasCheckConstraint("ck_heroes_name", "length(name) BETWEEN 1 AND 64");

                            t.HasCheckConstraint("ck_heroes_strain", "strain BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_heroes_success_streak", "success_streak >= 0");

                            t.HasCheckConstraint("ck_heroes_total_xp", "total_xp BETWEEN 0 AND 9007199254740991");

                            t.HasCheckConstraint("ck_heroes_trust", "trust BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.Project", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("created_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("identity_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("workspace_fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("workspace_fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_workspace_fingerprint");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_display_name", "length(display_name) BETWEEN 1 AND 120");

                            t.HasCheckConstraint("ck_projects_identity_version", "identity_version = 'project-identity/1'");

                            t.HasCheckConstraint("ck_projects_workspace_fingerprint", "length(workspace_fingerprint) = 64");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.QuestSession", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("created_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("finished_at_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("goal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hero_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("locale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("project_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("quest_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("started_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("project_id");

                    b.HasIndex("hero_id", "project_id")
                        .IsUnique()
                        .HasDatabaseName("ux_quest_sessions_one_open_per_hero_project")
                        .HasFilter("status = 'open'");

                    b.ToTable("quest_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_quest_sessions_goal", "length(goal) BETWEEN 1 AND 500");

                            t.HasCheckConstraint("ck_quest_sessions_locale", "locale IN ('ru-RU','en-US')");

                            t.HasCheckConstraint("ck_quest_sessions_status", "status IN ('open','finished')");

                            t.HasCheckConstraint("ck_quest_sessions_status_finished_at", "(status = 'open' AND finished_at_utc IS NULL) OR (status = 'finished' AND finished_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_quest_sessions_title", "length(title) BETWEEN 1 AND 120");

                            t.HasCheckConstraint("ck_quest_sessions_type", "quest_type IN ('planning','research','coding','review','debugging','documentation','maintenance')");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.AppSettings", b =>
                {
                    b.HasOne("HeroPassport.Storage.Hero", null)
                        .WithMany()
                        .HasForeignKey("active_hero_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HeroPassport.Storage.QuestSession", b =>
                {
                    b.HasOne("HeroPassport.Storage.Hero", null)
                        .WithMany()
                        .HasForeignKey("hero_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroPassport.Storage.Project", null)
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
