// <auto-generated />
using HeroPassport.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroPassport.Infrastructure.Persistence.GeneratedMigrations
{
    [DbContext(typeof(HeroPassportDbContext))]
    partial class HeroPassportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("HeroPassport.Storage.AppSettings", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("active_hero_id")
                        .HasColumnType("TEXT");

                    b.Property<int>("auto_finish_quest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("auto_start_quest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("config_version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("created_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("locale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("presentation_style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("project_identity_salt_v1")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("setup_completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("updated_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("active_hero_id");

                    b.ToTable("app_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_settings_auto_finish", "auto_finish_quest IN (0,1)");

                            t.HasCheckConstraint("ck_app_settings_auto_start", "auto_start_quest IN (0,1)");

                            t.HasCheckConstraint("ck_app_settings_config_version", "config_version >= 1");

                            t.HasCheckConstraint("ck_app_settings_locale", "locale IN ('ru-RU','en-US')");

                            t.HasCheckConstraint("ck_app_settings_presentation_style", "presentation_style IN ('rpg_engineering','classic_rpg','minimal')");

                            t.HasCheckConstraint("ck_app_settings_salt", "length(project_identity_salt_v1) = 32");

                            t.HasCheckConstraint("ck_app_settings_setup_active_hero", "(setup_completed = 0 AND active_hero_id IS NULL) OR (setup_completed = 1 AND active_hero_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_app_settings_setup_completed", "setup_completed IN (0,1)");

                            t.HasCheckConstraint("ck_app_settings_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.Hero", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("archived_at_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("created_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("strain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(20);

                    b.Property<long>("success_streak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<long>("total_xp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int>("trust")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(50);

                    b.Property<string>("updated_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("heroes", null, t =>
                        {
                            t.HasCheckConstraint("ck_heroes_name", "length(name) BETWEEN 1 AND 64");

                            t.HasCheckConstraint("ck_heroes_strain", "strain BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_heroes_success_streak", "success_streak >= 0");

                            t.HasCheckConstraint("ck_heroes_total_xp", "total_xp BETWEEN 0 AND 9007199254740991");

                            t.HasCheckConstraint("ck_heroes_trust", "trust BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.HeroProjectStats", b =>
                {
                    b.Property<string>("hero_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("project_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("last_quest_at_utc")
                        .HasColumnType("TEXT");

                    b.Property<long>("quests_finished")
                        .HasColumnType("INTEGER");

                    b.Property<long>("quests_started")
                        .HasColumnType("INTEGER");

                    b.Property<long>("quests_succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<long>("total_xp_earned")
                        .HasColumnType("INTEGER");

                    b.HasKey("hero_id", "project_id");

                    b.HasIndex("project_id");

                    b.ToTable("hero_project_stats", null, t =>
                        {
                            t.HasCheckConstraint("ck_hero_project_stats_quests_finished", "quests_finished >= 0");

                            t.HasCheckConstraint("ck_hero_project_stats_quests_started", "quests_started >= 0");

                            t.HasCheckConstraint("ck_hero_project_stats_quests_succeeded", "quests_succeeded >= 0");

                            t.HasCheckConstraint("ck_hero_project_stats_total_xp_earned", "total_xp_earned >= 0");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.HeroSkill", b =>
                {
                    b.Property<string>("hero_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("skill_key")
                        .HasColumnType("TEXT");

                    b.Property<string>("updated_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("hero_id", "skill_key");

                    b.HasIndex("skill_key");

                    b.ToTable("hero_skills", null, t =>
                        {
                            t.HasCheckConstraint("ck_hero_skills_xp", "xp BETWEEN 0 AND 9007199254740991");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.MutationReceipt", b =>
                {
                    b.Property<string>("operation_key")
                        .HasColumnType("TEXT");

                    b.Property<string>("request_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("args_encoding_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("args_hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("effective_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hero_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("project_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("result_entity_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("result_kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("result_status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("operation_key", "request_id");

                    b.ToTable("mutation_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_mutation_receipts_args_hash", "length(args_hash) = 32");

                            t.HasCheckConstraint("ck_mutation_receipts_operation", "operation_key IN ('bootstrap','create_hero','start_quest','finish_quest')");

                            t.HasCheckConstraint("ck_mutation_receipts_result_kind", "result_kind IN ('bootstrap','hero','quest_start','quest_finish')");

                            t.HasCheckConstraint("ck_mutation_receipts_result_status", "result_status IN ('active','target_deleted')");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.Project", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("created_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("identity_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("workspace_fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("workspace_fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_workspace_fingerprint");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_display_name", "length(display_name) BETWEEN 1 AND 120");

                            t.HasCheckConstraint("ck_projects_identity_version", "identity_version = 'project-identity/1'");

                            t.HasCheckConstraint("ck_projects_workspace_fingerprint", "length(workspace_fingerprint) = 64");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.QuestReport", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("active_title_after")
                        .HasColumnType("TEXT");

                    b.Property<string>("active_title_before")
                        .HasColumnType("TEXT");

                    b.Property<int>("base_xp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("bonus_xp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("build_evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("build_status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("created_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("finalization_args_encoding_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("finalization_args_hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("hero_level_after")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hero_level_before")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hero_progression_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("hero_total_xp_after")
                        .HasColumnType("INTEGER");

                    b.Property<long>("hero_total_xp_before")
                        .HasColumnType("INTEGER");

                    b.Property<int>("outcome_permille")
                        .HasColumnType("INTEGER");

                    b.Property<int>("penalty_xp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("quest_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rank_after")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rank_before")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rank_rule_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("raw_xp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("reward_rule_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("scope_violations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("skill_allocation_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("skill_progression_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("strain_after")
                        .HasColumnType("INTEGER");

                    b.Property<int>("strain_before")
                        .HasColumnType("INTEGER");

                    b.Property<long>("streak_after")
                        .HasColumnType("INTEGER");

                    b.Property<long>("streak_before")
                        .HasColumnType("INTEGER");

                    b.Property<string>("streak_rule_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tests_evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("tests_mentioned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tests_status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("trust_after")
                        .HasColumnType("INTEGER");

                    b.Property<int>("trust_before")
                        .HasColumnType("INTEGER");

                    b.Property<string>("trust_strain_rule_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("unlock_rule_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("user_corrections")
                        .HasColumnType("INTEGER");

                    b.Property<long>("xp_gained")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("quest_id")
                        .IsUnique()
                        .HasDatabaseName("ux_quest_reports_quest_id");

                    b.ToTable("quest_reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_quest_reports_build_evidence", "build_evidence IN ('observed','reported','none')");

                            t.HasCheckConstraint("ck_quest_reports_build_status", "build_status IN ('not_run','passed','failed','unknown')");

                            t.HasCheckConstraint("ck_quest_reports_finalization_hash", "length(finalization_args_hash) = 32");

                            t.HasCheckConstraint("ck_quest_reports_levels", "hero_level_before BETWEEN 1 AND 50 AND hero_level_after BETWEEN 1 AND 50");

                            t.HasCheckConstraint("ck_quest_reports_outcome_permille", "outcome_permille IN (0,100,300,600,1000)");

                            t.HasCheckConstraint("ck_quest_reports_result", "result IN ('success','partial','blocked','failed','abandoned')");

                            t.HasCheckConstraint("ck_quest_reports_scope_violations", "scope_violations BETWEEN 0 AND 20");

                            t.HasCheckConstraint("ck_quest_reports_strain", "strain_before BETWEEN 0 AND 100 AND strain_after BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_quest_reports_streak", "streak_before >= 0 AND streak_after >= 0");

                            t.HasCheckConstraint("ck_quest_reports_summary", "length(summary) BETWEEN 1 AND 2000");

                            t.HasCheckConstraint("ck_quest_reports_tests_evidence", "tests_evidence IN ('observed','reported','none')");

                            t.HasCheckConstraint("ck_quest_reports_tests_mentioned", "tests_mentioned IN (0,1)");

                            t.HasCheckConstraint("ck_quest_reports_tests_status", "tests_status IN ('not_run','passed','failed','unknown')");

                            t.HasCheckConstraint("ck_quest_reports_total_xp", "hero_total_xp_before BETWEEN 0 AND 9007199254740991 AND hero_total_xp_after BETWEEN 0 AND 9007199254740991");

                            t.HasCheckConstraint("ck_quest_reports_trust", "trust_before BETWEEN 0 AND 100 AND trust_after BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_quest_reports_user_corrections", "user_corrections BETWEEN 0 AND 20");

                            t.HasCheckConstraint("ck_quest_reports_xp_components", "base_xp >= 0 AND bonus_xp >= 0 AND penalty_xp >= 0 AND raw_xp >= 0 AND xp_gained >= 0");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.QuestReportSkill", b =>
                {
                    b.Property<string>("quest_report_id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("level_after")
                        .HasColumnType("INTEGER");

                    b.Property<int>("level_before")
                        .HasColumnType("INTEGER");

                    b.Property<string>("skill_key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("xp_after")
                        .HasColumnType("INTEGER");

                    b.Property<long>("xp_before")
                        .HasColumnType("INTEGER");

                    b.Property<long>("xp_gained")
                        .HasColumnType("INTEGER");

                    b.HasKey("quest_report_id", "ordinal");

                    b.HasIndex("skill_key");

                    b.HasIndex("quest_report_id", "skill_key")
                        .IsUnique()
                        .HasDatabaseName("ux_quest_report_skills_report_skill");

                    b.ToTable("quest_report_skills", null, t =>
                        {
                            t.HasCheckConstraint("ck_quest_report_skills_level_after", "level_after BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_quest_report_skills_level_before", "level_before BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_quest_report_skills_ordinal", "ordinal BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_quest_report_skills_xp_after", "xp_after BETWEEN 0 AND 9007199254740991");

                            t.HasCheckConstraint("ck_quest_report_skills_xp_before", "xp_before BETWEEN 0 AND 9007199254740991");

                            t.HasCheckConstraint("ck_quest_report_skills_xp_gained", "xp_gained BETWEEN 0 AND 9007199254740991");

                            t.HasCheckConstraint("ck_quest_report_skills_xp_monotonic", "xp_after = xp_before + xp_gained");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.QuestRewardComponent", b =>
                {
                    b.Property<string>("quest_report_id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("component_key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("xp_delta")
                        .HasColumnType("INTEGER");

                    b.HasKey("quest_report_id", "ordinal");

                    b.HasIndex("quest_report_id", "component_key")
                        .IsUnique()
                        .HasDatabaseName("ux_quest_reward_components_report_key");

                    b.ToTable("quest_reward_components", null, t =>
                        {
                            t.HasCheckConstraint("ck_quest_reward_components_delta", "xp_delta BETWEEN -9007199254740991 AND 9007199254740991 AND xp_delta <> 0");

                            t.HasCheckConstraint("ck_quest_reward_components_key", "length(component_key) BETWEEN 1 AND 80");

                            t.HasCheckConstraint("ck_quest_reward_components_ordinal", "ordinal >= 0");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.QuestSession", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("created_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("finished_at_utc")
                        .HasColumnType("TEXT");

                    b.Property<string>("goal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hero_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("locale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("project_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("quest_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("started_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("project_id");

                    b.HasIndex("hero_id", "project_id")
                        .IsUnique()
                        .HasDatabaseName("ux_quest_sessions_one_open_per_hero_project")
                        .HasFilter("status = 'open'");

                    b.ToTable("quest_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_quest_sessions_goal", "length(goal) BETWEEN 1 AND 500");

                            t.HasCheckConstraint("ck_quest_sessions_locale", "locale IN ('ru-RU','en-US')");

                            t.HasCheckConstraint("ck_quest_sessions_status", "status IN ('open','finished')");

                            t.HasCheckConstraint("ck_quest_sessions_status_finished_at", "(status = 'open' AND finished_at_utc IS NULL) OR (status = 'finished' AND finished_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_quest_sessions_title", "length(title) BETWEEN 1 AND 120");

                            t.HasCheckConstraint("ck_quest_sessions_type", "quest_type IN ('planning','research','coding','review','debugging','documentation','maintenance')");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.Skill", b =>
                {
                    b.Property<string>("skill_key")
                        .HasColumnType("TEXT");

                    b.HasKey("skill_key");

                    b.ToTable("skills", null, t =>
                        {
                            t.HasCheckConstraint("ck_skills_key", "skill_key IN ('coding','testing_awareness','scope_control','documentation','tool_use','planning','research','debugging','review','maintenance')");
                        });

                    b.HasData(
                        new
                        {
                            skill_key = "coding"
                        },
                        new
                        {
                            skill_key = "testing_awareness"
                        },
                        new
                        {
                            skill_key = "scope_control"
                        },
                        new
                        {
                            skill_key = "documentation"
                        },
                        new
                        {
                            skill_key = "tool_use"
                        },
                        new
                        {
                            skill_key = "planning"
                        },
                        new
                        {
                            skill_key = "research"
                        },
                        new
                        {
                            skill_key = "debugging"
                        },
                        new
                        {
                            skill_key = "review"
                        },
                        new
                        {
                            skill_key = "maintenance"
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.XpEvent", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("created_at_utc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hero_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("project_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("quest_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("reward_rule_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("xp_delta")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("hero_id");

                    b.HasIndex("project_id");

                    b.HasIndex("quest_id")
                        .IsUnique()
                        .HasDatabaseName("ux_xp_events_quest_id");

                    b.ToTable("xp_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_xp_events_xp_delta", "xp_delta >= 0");
                        });
                });

            modelBuilder.Entity("HeroPassport.Storage.AppSettings", b =>
                {
                    b.HasOne("HeroPassport.Storage.Hero", null)
                        .WithMany()
                        .HasForeignKey("active_hero_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HeroPassport.Storage.HeroProjectStats", b =>
                {
                    b.HasOne("HeroPassport.Storage.Hero", null)
                        .WithMany()
                        .HasForeignKey("hero_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroPassport.Storage.Project", null)
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroPassport.Storage.HeroSkill", b =>
                {
                    b.HasOne("HeroPassport.Storage.Hero", null)
                        .WithMany()
                        .HasForeignKey("hero_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroPassport.Storage.Skill", null)
                        .WithMany()
                        .HasForeignKey("skill_key")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroPassport.Storage.QuestReport", b =>
                {
                    b.HasOne("HeroPassport.Storage.QuestSession", null)
                        .WithMany()
                        .HasForeignKey("quest_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroPassport.Storage.QuestReportSkill", b =>
                {
                    b.HasOne("HeroPassport.Storage.QuestReport", null)
                        .WithMany()
                        .HasForeignKey("quest_report_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroPassport.Storage.Skill", null)
                        .WithMany()
                        .HasForeignKey("skill_key")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroPassport.Storage.QuestRewardComponent", b =>
                {
                    b.HasOne("HeroPassport.Storage.QuestReport", null)
                        .WithMany()
                        .HasForeignKey("quest_report_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroPassport.Storage.QuestSession", b =>
                {
                    b.HasOne("HeroPassport.Storage.Hero", null)
                        .WithMany()
                        .HasForeignKey("hero_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroPassport.Storage.Project", null)
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroPassport.Storage.XpEvent", b =>
                {
                    b.HasOne("HeroPassport.Storage.Hero", null)
                        .WithMany()
                        .HasForeignKey("hero_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroPassport.Storage.Project", null)
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeroPassport.Storage.QuestSession", null)
                        .WithMany()
                        .HasForeignKey("quest_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
